<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Zack Market_userHeader_tag__1GnYA</name>
   <tag></tag>
   <elementGuidId>0838b988-eca0-4408-b2ec-e61018afbbd4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.userHeader_loggout__1ayRn > div.userHeader_tag__1GnYA</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.userHeader_loggout__1ayRn > .userHeader_tag__1GnYA</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7f4d7c8b-63e6-402f-9bb7-faac97d0b2f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>userHeader_tag__1GnYA</value>
      <webElementGuid>ac23926f-8bc6-4cfb-aaa2-788e8065006c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;dashboard_outbox__1Z8DY&quot;]/div[@class=&quot;header_outbox__2AJDK&quot;]/div[1]/div[@class=&quot;userHeader_outbox__3_BoI&quot;]/div[@class=&quot;userHeader_loggout__1ayRn&quot;]/div[@class=&quot;userHeader_tag__1GnYA&quot;]</value>
      <webElementGuid>dbf3d546-885b-4c14-8bb7-c6ddcda0055e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/div[2]/div</value>
      <webElementGuid>118d364e-8017-4ff5-8cb8-ff28ac4fa064</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zack Market'])[2]/preceding::div[1]</value>
      <webElementGuid>7d6a3c1e-81e8-4c25-9501-20c5e2204f4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Products'])[1]/preceding::div[10]</value>
      <webElementGuid>8f527307-e163-47c2-a8a8-408db11ac3a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div[2]/div</value>
      <webElementGuid>7c85d19e-0487-4e02-8ef8-43b36559ae08</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
