public class BMICalcu {
    public static void main(String[] args) {
        System.out.println("BMI Calculator");
        int weight = 60;
        int height = 170;
        double bmi = weight/Math.pow(height/100,b:2);
        System.out.println("Result: " + bmi);

        // Array
        String[] cars = {"Volco", "BMW", "Wuling"};
        cars[0] = "Wuling";
        System.out.println(cars[0]);
    }
}